### ISSUE TITLE
Event card font sizes (mobile view)

### ISSUE THREAD

**Issue by xumaple** [hmcc-global/hmccaa-web#133]
(phil's thoughts)

- title of card should be larger than speaker info
- need a bit more margin space on the left of all text
- date needs to be a bit bigger, maybe 1-2pts, rn it's too small for maple's blind eyes

(this is only for mobile, desktop looks good)

**Comment by initialdpw** [comment]
for desktop and mobile, would like thicker border and stronger shadow.

for mobile spacing and fonts, see image below: 
<img width="298" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/1b1e4d2d-4674-4268-b6d5-96dc35bd68cb">

**Comment by thedomcab** [comment]
two version of the improve shadow:
![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/a533f539-8aa9-493d-be16-41620b4b3915)

![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/2b3e18e3-38f9-47a6-b001-401474c568f9)
