### ISSUE TITLE
Buttons (Hover State)

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#145]
For buttons, would like to have a change in style for the hover state. 
- Mostly, change text to the ORANGE PINK color (FF8069) we've been using. 
- For buttons without borders (where link is already pink), increase font size by 2 pt. (i.e. if font is 16 pt, then hover would be 18 pt, same color). 
- See image below for all of these.
<img width="673" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/899a2d83-1fd3-4592-9fb2-b18c35dc4559">

**Comment by initialdpw** [comment]
Don't mean to add more work but would like to reopen button hover state. If it's too much, I would focus on just the I'M NEW button. I think this is one of the most important button, so the user experience is important for this one.

In general, emphasize the color change and increase text size a bit (from 16 to 18 px in hover. this in turn enlarges the button as well, as the button has padding 20 px left and 20 px right and 12 px top and 12 px bottom.

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/172c4895-22da-46c2-855e-128dfac7fc30)
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/e81a206d-a9bd-41c6-8cc9-7c0b7a8ba087)

**Comment by terrianx** [comment]
did most of the changes u requested but i have some concerns with the text size changing. when hovering a lot of other elements shift around. in some places its much worse than others but it is ubiquitous (although there are places where shifting does not occur). it can be distracting sometimes. if you want to see other examples let me know. 

in my opinion, changing the sizing without shifting other elements would be a difficult and perhaps should not be prioritized when we are trying to get this website deployed in a few weeks. but also if you or anyone else feels strongly about this point of ux then ill continue working on it.

https://github.com/hmcc-global/hmccaa-web/assets/88253868/2768177f-7589-4fee-b1db-ecf1dcd37249

https://github.com/hmcc-global/hmccaa-web/assets/88253868/46f558da-a756-4544-a52b-7bb3a700fa31

**Comment by initialdpw** [comment]
ah i see. ignore the size then. i think the color change is good. we can revisit in later future if anything. wouldn't worry about it for launch.
