### ISSUE TITLE
Make Instagram bar more clickable

### ISSUE THREAD

**Issue by xumaple** [hmcc-global/hmccaa-web#164]
Maybe make the `@HMCC_AA` underlined? or something to communicate that we can click on this bar

**Comment by thedomcab** [comment]
Does this look good:
![image](https://github.com/hmcc-global/hmccaa-web/assets/9808478/9d03208f-a8db-4f8c-a247-3349214bf1a7)

**Comment by xumaple** [comment]
yes!
