### ISSUE TITLE
Watch page bugs

### ISSUE THREAD

**Issue by hmccaa** [hmcc-global/hmccaa-web#221]
- [x] click on "Books" -> shows "Select a Books" instead of "Select a Book"
- [  ]Sermon Series picture is not being correctly displayed for each sermon
- Page numers:
    1) - [x]  Page number seems really big to me? 
    2) - [  ]can we show no page number if there's only one page?
- [  ] Missing Sermon topics
- [x] When I choose a category to sort by, it brings me to a new page all the way to the top again. Is there a way to bring me partially down so I don't need to keep scrolling down?
- [x] Dates being shown should not show the time (currently shows 12AM)

**Comment by xumaple** [comment]
most of this is resolved. unresolved will be opened up as more issues. closing.
