### ISSUE TITLE
Reroute/edit links (and description) for Member, Ministry, Baptism classes, Transformation classes

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#222]
1. Redirect links for Membership page, Ministry Team page, Baptism page and Transformation class page to EVENTS page. (See image below as one example. Rest are in Figma file.)
<img width="671" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/7a22f622-b564-4fec-8407-1f7d0023d4d3">

2. Edit EVENTS page - add one line under all the events card to note that these classes are offered twice a year (see image below)
<img width="537" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/eaf90a1c-955a-4930-b18e-f3b4e327c66d">

**Comment by terrianx** [comment]
specifically these links:

1. pages/next-steps/baptism - sign up for baptism class
2. pages/next-steps/membership - become a member
3. pages/next-steps/transformation - sign up now
