### ISSUE TITLE
connect with us main page questionnaire missing

### ISSUE THREAD

**Issue by terrianx** [hmcc-global/hmccaa-web#223]
description says the link is to a questionnaire but it currently links to the connect page. replace with actual link or change text to make it clear that the link points to the connect page.

<img width="791" alt="Screenshot 2024-04-11 at 3 40 42 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/413af926-da44-4f92-a739-7babce9111d9">

**Comment by initialdpw** [comment]
Can we group this and issue #225 together? along with the first button from the I'm New page ("Let Us Know You're Coming".

For all 3, use the link: https://fs23.formsite.com/whitemn/dtuolqqeba/index.html
