### ISSUE TITLE
[About/Our Team] Text Updates

### ISSUE THREAD

**Issue by Brandt-Bowling** [hmcc-global/hmccaa-web#253]
- [x] Add Danny & Phi Bang
- [x] Add '#' to Nate's card (#Outreach)
- [x] Reorder cards to Name -> email -> # section
- [x] Break out each "#" description onto its own line
<img width="319" alt="Screenshot 2024-05-24 at 11 48 18 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/16947840/ef638d5d-1405-44ef-be71-d874a064d1af">

**Comment by initialdpw** [comment]
Added danny and phi images in gdrive: https://drive.google.com/drive/folders/178SueYt_Snx5tjQuZz6IGR_TCRNUFnQ1?usp=drive_link

<img width="776" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/3271734c-ab5b-4568-bc4f-b2195d4ed3a7">

For emails and info, go to current hmcc site: https://annarbor.hmcc.net/leaders/
