### ISSUE TITLE
[About] Update Beliefs & Add link to distinctives

### ISSUE THREAD

**Issue by Brandt-Bowling** [hmcc-global/hmccaa-web#259]
Should match what's at https://annarbor.hmcc.net/about/beliefs/ with a link to the google doc outlining the theological distinctives

**Comment by terrianx** [comment]
There is nothing on the figma that gives guidelines of what to do for the link. Is this task completely up to me on how it should be designed as well?

**Comment by terrianx** [comment]
theres a Jesus section _and_ a salvation section on the new website, but on the old one its salvation through Jesus. there doesnt seem to be a clear answer as to how the text should be matched. should each of the headings be changed to match the old website? There are a quite a few differences with the sections.

<img width="1126" alt="Screenshot 2024-06-09 at 6 53 52 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/b627fd31-2da6-4ff7-a9d4-068df090adde">
<img width="1105" alt="Screenshot 2024-06-09 at 6 54 04 PM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/a6fb5ced-99e3-4404-bebd-b86b47349042">

**Comment by initialdpw** [comment]
this was new direction that i was not aware of til yesterday. confirmed on the change to current website. I just updated Figma doc.
