### ISSUE TITLE
[About] Spacing on mobile for 'our values'

### ISSUE THREAD

**Issue by Brandt-Bowling** [hmcc-global/hmccaa-web#260]
<img width="321" alt="Screenshot 2024-05-25 at 12 11 12 AM" src="https://github.com/hmcc-global/hmccaa-web/assets/16947840/3727c8e1-72c8-4fa1-90e6-16fcc5b36e96">

**Comment by initialdpw** [comment]
only checked on desktop view but spacing between each section is too tight/close (see "our beliefs" section). Maybe it's a just increasing the initial spacing between each line, before you click into each one. 

<img width="785" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/b8a9c6a9-c6bc-48c2-938a-55a036bb0295">
