### ISSUE TITLE
[ALL Pages] Vertical white spaces in between sections/End

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#278]
Can we increase the white vertical spacing in between each section? Ideally at least 120 px between each section (maybe 60 px top and bottom). i know this can be a bit vague and not apply to all sections, so if it's confusing, ignore but please do the following:

1. Increase white spacing of the last section and footer to 160+ px
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/c0975191-f15e-4e8d-bc43-0b4894df0635)

2. Increase this specific section vertical spacing on home page, at least 120 px, though probably prefer 160 px
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/4c71c789-7e0a-461d-af0e-01538074d053)

**Comment by initialdpw** [comment]
There are a few other vertical spacing items I see. would

ABOUT page: Please use 60 px between the words and pics:
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/a9a6ba42-cc91-4a0b-a935-3d5d19a755d9)

HOME page: Please use 20 px between heading and body text (i realized that maybe based on how fonts work in WEB vs FIGMA file, maybe there's discrepancy with pixel/spacing? if it looks tight, please add more spacing, similar to other sections)
<img width="634" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/14e45160-b090-4726-aba7-03cf1d33f8a0">

Those are the major ones i see currently. 

(note: in future, i'd love to rework on the spacing for ALL components - i.e. button to text, etc. learning more in uiux and wished i knew more back then when I first designed)

**Comment by terrianx** [comment]
i made a 200px tall blue section to show where the padding would appear in all the pages. some pages have other graphical elements attached to the footer such as these below. i assume i would just ignore these pages? and then for the feedback form one the blue background section should just be expanded more down?

<img width="1440" alt="Screenshot 2024-07-08 at 1 21 43 AM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/6296c91e-a9fb-49ec-ba56-d81c914d19ce">
<img width="1440" alt="Screenshot 2024-07-08 at 1 22 06 AM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/50eb5131-0edf-4185-a471-824666244f8f">
<img width="1440" alt="Screenshot 2024-07-08 at 1 24 24 AM" src="https://github.com/hmcc-global/hmccaa-web/assets/88253868/1ba6bbfe-f895-4ad5-a822-1e78f97b2da5">

**Comment by initialdpw** [comment]
let's say 160px at the end of every page. (note: i edited the original post to say 160 instead of 200)

i.e.
<img width="461" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/8f27624c-33b7-45cb-b2cd-64c9401ce91b">
<img width="319" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/a04ffea7-8967-4b98-bdfc-0bc410cd8889">
<img width="450" alt="image" src="https://github.com/hmcc-global/hmccaa-web/assets/136141441/1817081c-f3eb-40f9-9138-01dbbe3fbdac">
