### ISSUE TITLE
[Home] New design for first image

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#287]
Would like to redesign front image to make it look nicer especially as it's the first thing ppl see. 

Notes:
1. "Transform Lives, Transform the World" text is in BEBAS KAI at 48 pt and 6% letter spacing
2. Can we make the main bg image stay still for a bit while the text scrolls? (the text scrolls normally. the image behind stays for a while and then shifts. see as example: https://www.anchorcollegechurch.org/ )
3. Blue background for "JOIN US THIS SUNDAY" is still hex color #D0E3ED but 90% opacity.
4. Not sure what horizontal spacing between "JOIN US THIS SUNDAY" and "CELEBRATION TIME" currently is, but can we make it 100 px spacing? Or if it's already that, then make it 80 px? it looks rather far apart.
5. Make "Sunday Celebration Time" ALL CAPS and color #0C2966 (or a dark blue that's already been used before)
6. I uploaded the proper image in [gdrive](https://drive.google.com/drive/folders/178SueYt_Snx5tjQuZz6IGR_TCRNUFnQ1?usp=drive_link) under H-1cover (main)
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/a1a182fa-4ebe-4e1f-bbd2-1dd926b8bcc0)

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/421bd806-1d92-4aba-8920-0efa8c45221f)

**Comment by initialdpw** [comment]
Sorry, hold up on these actually if you haven't started. I'm kind of looking into alternate design. Not sure if people have thoughts. I feel like the first image has the "JOIN US" info way bigger that it overshadows the "TRANSFORM LIVES..." 
 
![image](https://github.com/user-attachments/assets/7b0800b5-a4d7-406e-b803-6ca8f75b8788)

**Comment by xumaple** [comment]
verdict: go with the most recently posted one

**Comment by initialdpw** [comment]
@thedomcab font sizes and style: 
![image](https://github.com/user-attachments/assets/91686752-ec5d-427b-aa48-d76360fb7ac2)
