### ISSUE TITLE
[ABOUT>HMCC PARTNERS] link proper page + add flag icons and stm formats

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#291]
Make sure link from ABOUT > HMCC PARTNERS goes to the correct page.

In the HMCC PARTNERS page, i uploaded the [flags in gdrive](https://drive.google.com/drive/folders/1vrBw6CfE0qltrcFvLWU-PUpsLGo-qqPK?usp=drive_link).

Some notes for fonts:
i.e. MEXICO - 20 pt, color #4352B1
i.e. 1999 - 16 pt, color (standard black you use for regular text)

Some notes for spacing:
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/79dd36ba-7898-46bf-8e07-ccc4b5a4f0d2)

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/fd7247a3-c60f-4ae7-8cd8-e117ace95f4c)

**Comment by thedomcab** [comment]
@initialdpw could you explain: "Make sure link from ABOUT > HMCC PARTNERS goes to the correct page." I need more info on what you mean.

**Comment by initialdpw** [comment]
hmms, it looks like the link is good now so nevermind on that part
