### ISSUE TITLE
[ABOUT>HMCC PARTNERS] update links in supported workers section

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#292]
not seeing the page so unsure if it's updated but for all the "MORE INFO" links under SUPPORTED WORKERS of the HMCC PARTNERS page, please link:

ROBERT & KARYN BARRIGER - caminodevida.com
HMCC Pastors - to their respective hmcc sites
TIMOTHY & MIRIAM HARRIS - https://lovingyourmuslimneighbor.com/
T&J - no links

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/1da2fdd4-1434-49f9-a7c9-5d99aee768bf)

**Comment by Brandt-Bowling** [comment]
This was addressed via #277
