### ISSUE TITLE
[NEXT STEPS>MINISTRY TEAMS] Update Ministry Team page pictures and layout

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#293]
Wanted to have more pictures and more personal pictures of our teams in action.

Photos uploaded in gdrive: https://drive.google.com/drive/folders/19HSNhALfkpstJbQtd4HDKGGoTHbQgvTy?usp=drive_link

Similar layout/style to Life Groups page. smaller photos 280 px wide and 20 px in between
![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/8055e5fb-f972-4a71-8c1b-9b7a37bfe37f)

**Comment by initialdpw** [comment]
@Brandt-Bowling looks like you completed this. i did update Figma but basically more or less the same as the screenshot i sent prior in Teams chat

![image](https://github.com/user-attachments/assets/21304d6a-27f0-4242-911d-02b76af5130c)

**Comment by Brandt-Bowling** [comment]
> @Brandt-Bowling looks like you completed this. i did update Figma but basically more or less the same as the screenshot i sent prior in Teams chat
> 
> ![image](https://github.com/user-attachments/assets/21304d6a-27f0-4242-911d-02b76af5130c)
> 

Let me know if what I submitted should be tweaked

**Comment by initialdpw** [comment]
looks good for most part. i think we'd want to standardize the font-size and spacings across all the pages at some point. i.e. LIFE GROUP page title font is bigger than the others. vertical spacings might differ too. i will try to create new issue for this instead of putting on this ministry page issue since it's more of a site-wide thing.
