### ISSUE TITLE
[Re-edit] Footer - delete terms & policy link

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#30]
For the footer, please delete "terms & conditions" and "policy" link on bottom right corner. Also remove the horizontal line. See newest design in Figma /image attached.

![image](https://github.com/hmcc-global/hmccaa-web/assets/136141441/f983677a-18fe-4ceb-90fb-2653e48018e2)

**Comment by thedomcab** [comment]
i think I took care of this already in my about us page. i will make a PR this weekend for this, since the last piece of the about us page is in master already. and will be done with the about us page with footer all good.

**Comment by xumaple** [comment]
@thedomcab was this resolved? If so (or even if you have an open PR for it) can you link the PR for it?
