### ISSUE TITLE
[mobile][Hamburger Menu] clicking on "I'm New"

### ISSUE THREAD

**Issue by xumaple** [hmcc-global/hmccaa-web#331]
Mobile view hamburger menu: clicking on "I'm New" only works when clicking on text, not when clicking anywhere else on that row

**Comment by xumaple** [comment]
also would help UX to give some visual cue when a finger touches any of the rows (maybe with a lighter grey in that section?) @initialdpw thoughts on this?

**Comment by initialdpw** [comment]
agreed. please make whole bar clickable for all pages in mobile menu bar.
for visual cue when finger touches button:
 - For all pages: use primary/300 (#1A56D6) on the whole bar
 - For the I'm New specifically: please make a fill in the same color as the stroke (FF8069) - similar to desktop mode hover. see below image.
![image](https://github.com/user-attachments/assets/95f77254-c74f-465c-bbe2-5b3d6a35a88b)

--
is there a way to make the "I'm New" text font bigger? it's much smaller than the other fonts.
and have the "I'm New" spacing be same as all the other (from the left side). if that's not feasible, probably better to make I'm New centered-aligned instead.

![image](https://github.com/user-attachments/assets/e1d8c23f-62df-48e2-9b77-d5ac8096be6f)

**Comment by initialdpw** [comment]
apologies on poor explanation but hopefully the following helps. If you have questions, let me know. 

From current dev site: 
- for the normal state - need to change I'm New
- for the hover state - i.e. if a person starts on About page, and then clicks on a different page (i.e. Watch), right when he clicks the Watch button, it will highlight Watch button in blue right before it loads the Watch page.

![image](https://github.com/user-attachments/assets/7abb8885-eb48-49cb-a79b-e9bc32e3afe8)
