### ISSUE TITLE
[mobile][SECTION PADDING] Add 80 px padding top and bottom for sections with BORDERS

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#350]
For all sections with rounded borders, please use a 80 px PADDING TOP and BOTTOM. See images.

ONLY exception is the EVENTS>PRAYER section. (i should've designed this entire section differently but for now, say 40 px padding top and bottom)

![image](https://github.com/user-attachments/assets/d3ad27ca-437c-4d71-a104-d34e69cdcec9)
![image](https://github.com/user-attachments/assets/1c16790a-455c-4245-bd35-805790aa4e3a)

**Comment by Brandt-Bowling** [comment]
@initialdpw is this only for mobile? or everything

**Comment by initialdpw** [comment]
just mobile. i think i might've created a setting for desktop in the past but if not, i'll create separate issue. this one just for mobile

**Comment by Brandt-Bowling** [comment]
@initialdpw gotcha. Do you want it on event cards as well? Also, I did the 40px for the sunday celebration section of the events page similar to the prayer gathering. Thoughts?
<img width="275" alt="Screenshot 2024-10-07 at 8 27 16 PM" src="https://github.com/user-attachments/assets/fd67ca37-8083-4d91-9fe2-12dc19bce295">

**Comment by initialdpw** [comment]
hmms, i see. yeah, i think it's fine. i don't like the fonts for "@" symbols and will probably redesign this later (unrelated to spacing). but for now, yeah, i think it's good!
