### ISSUE TITLE
[SEO Meta Descriptions] Text for each page

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#388]
HOME - Welcome to Ann Arbor! We're a church on the University of Michigan campus that is open to people of all life stages and backgrounds. Come visit us on Sundays at 10 am!
 
ABOUT US - HMCC's mission is to transform lost people into Christ's disciples who will then transform the world. We do this by gathering, growing, and going. Learn more about us!
 
CONNECT - Find out more about HMCC - when and where we meet, frequently asked questions, or simply say hi so we can connect with you!
 
NEXT STEPS - Come check out our Life Groups, where we encourage each other in our journey of faith! Also, learn more about membership, ministry teams, and missions.
 
UPCOMING EVENTS - Events are ways we gather as a church body to connect across different life stages. Don’t miss out on opportunities to have fun and get to know others!
 
WATCH ONLINE - Please join us in person on Sundays at the T-center. But if you cannot, come worship with us through our live stream! You can find our past sermons here too.
 
GIVING - If you're interested in supporting what God is doing here at Harvest Mission Community Church, there are a couple options you can give.
 
I'M NEW - Welcome to HMCC! We are on the University of Michigan campus and are open to people of all life stages and backgrounds. We'd love to get to know you.

**Comment by initialdpw** [comment]
Here's some more for the subpages:

OUR TEAM (/about/our-team/) - Get to know a bit more about our elders and deacons at HMCC. Feel free to reach out for any questions you may have.

LIFE GROUPS (/next-steps/lifegroups/) - 
Life Group is an avenue to develop Christ-centered relationships. There's no better way to get a taste of who we are and what we believe in than through Life Groups! 

HMCC PARTNERS - (/about/hmi/) - 
HMI is our outreach ministry, committed to planting churches, sending workers, and partnering with missionaries. We have church plants in Austin, Jakarta, Tangerang, Hong Kong, and Detroit.


MEMBERSHIP (/next-steps/membership/) - 
As believers in Jesus, we are members of his spiritual body, demonstrated by a commitment to the local church. Find out what membership at HMCC looks like!


BAPTISM (/next-steps/baptism/) - 
Baptism represents a union with Jesus in his death and resurrection, which is only possible through saving faith in him. Learn more about baptism here at HMCC. 


MINISTRY TEAMS (/next-steps/ministryteams/) - 
God has given us unique gifts to build up the church and the world around us. Check out some possible ways we can serve one another as a church body!


LIFE STAGES - (/?/lifestages) -
Whether you’re coming for school or are in Michigan for family or career, we have a group for you! Learn more about the different Life Stages at HMCC.


TRANSFORMATION CLASSES (/next-steps/transformation/) - 
Transformation classes are meant to help challenge, encourage, and equip our members to know God more deeply and live out His calling for their lives.


MISSIONS SUPPORT - (/next-steps/missions/) - 
God has called each of us to missions, whether overseas or local. We send out mission teams each year to various places. See how you can support or get involved!

**Comment by xumaple** [comment]
@initialdpw  pretty sure nobody ever fills out the Sermon description. any ideas for what to use there instead?

**Comment by initialdpw** [comment]
hmms, i see. Can you auto-attach the other given info as the meta description? 

SERMON (individual sermon page) - [date][sermon title][passage][speaker]
