### ISSUE TITLE
[I'M NEW] + [CONNECT] Delete CONNECT page and move some of its content to I'M NEW

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#428]
Please move the HMCC PARKING MAP and the COMMON QUESTION sections from [CONNECT] page to [I'M NEW] page. Then delete the [CONNECT] page entirely.

Note: This issue is just to move content. Another issue will be for changing the style of the content.
***Also, please make sure all the links are properly routed to I'm New as needed. 

![image](https://github.com/user-attachments/assets/94802a26-7ed3-4dcb-8d64-aaab45ea1064)

**Comment by Brandt-Bowling** [comment]
@initialdpw Where should the /connect/life-stages page originate now?

**Comment by Brandt-Bowling** [comment]
<img width="306" alt="Screenshot 2024-10-08 at 3 09 27 PM" src="https://github.com/user-attachments/assets/15195731-6020-4549-968b-07f6ff3aca48">


@initialdpw will there be no more need for this component as well?

**Comment by initialdpw** [comment]
good questions:
1. is it okay to have the lifestages page be nested under get-involved (previously next-steps)? if we don't have an internal link from 'get-involved' to 'lifestages", will there be any SEO and indexing issues? if there's issues, i can create small section in 'get-involved' page to link to 'lifestages'
2. correct, no need for the component you screenshotted on the I'm New page. however, now i look at this, it might be good to replace this component with the current one in the Events page. Can you please do that? or should i open new issue?

**Comment by Brandt-Bowling** [comment]
1. I think @mapxu would know better but I'd assume not having an organic link would be not ideal.

2. I can do that for sure, but let's make it a separate issue 👍
