### ISSUE TITLE
[CONNECT]/[I'M NEW] Change style of the HMCC Parking Map and Common Questions sections

### ISSUE THREAD

**Issue by initialdpw** [hmcc-global/hmccaa-web#429]
Please change styles for the Parking Map section and the Common Questions sections.

Details of fonts and spacing in image. 

Parking Map bg color is Primary/700 or #0C2966
HMCC text color is #7AD1FF
10 AM and Address text color is #DAF14B

![image](https://github.com/user-attachments/assets/74f932fe-7c12-4e14-9fa8-d2906e584d4f)

**Comment by Brandt-Bowling** [comment]
@initialdpw Is the final draft of this in Figma? I didn't see it last I checked. Also, can you give me the padding you want between the top border and first text, and the bottom button and bottom border?
