### ISSUE TITLE
top bar above navbar currently white color

### ISSUE THREAD

**Issue by xumaple** [hmcc-global/hmccaa-web#99]
make it look better??

**Comment by terrianx** [comment]
firefox
![IMG_2379.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/1ed7c23a-cd6b-4ca1-85ea-7d21f2c92e88/5159431f-f7e2-4a7a-90a8-6981e082898c/IMG_2379.png)

safari
![IMG_2378.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/1ed7c23a-cd6b-4ca1-85ea-7d21f2c92e88/91f48b50-ae30-4402-8d77-3919eb1ff267/IMG_2378.png)

chrome - has default dark gray pull to refresh for dark mode iphone
![IMG_2377.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/1ed7c23a-cd6b-4ca1-85ea-7d21f2c92e88/d96d0c10-bb10-4e60-b661-0b2b4c4ddcd7/IMG_2377.png)

**Comment by terrianx** [comment]
https://github.com/hmcc-global/hmccaa-web/pull/115
